NDefines.NTitle.EMPIRE_DE_JURE_ASSIMILATION_YEARS = 100
NDefines.NTitle.GAME_RULES_DEJURE_LONG = 250
NDefines.NTitle.GAME_RULES_DEJURE_LONG_EMPIRE = 150
NDefines.NTitle.GAME_RULES_DEJURE_SHORT = 120
NDefines.NTitle.GAME_RULES_DEJURE_SHORT_EMPIRE = 85
NDefines.NTitle.GAME_RULES_DEJURE_SHORTEST = 70
NDefines.NTitle.GAME_RULES_DEJURE_SHORTEST_EMPIRE = 60
	
NDefines.NTitle.ALLOW_DE_JURE_ASSIMILATION_ANYWHERE = 0
