#!/bin/bash
source "scripts/common/paths.sh"

sed -i 's/"German_Middle_High"\(.*\)"\([^"]*[Ii]\)e\([^n][^"]*\)"/"German_Middle_High"\1"\2\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ww]\)n\([^"]*\)"/"German_Middle_High"\1"\2\3en\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Hh]\)eu\([^"]*\)"/"German_Middle_High"\1"\2\3iuw\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)aur\([^"]*\)"/"German_Middle_High"\1"\2our\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ss]\)ch\([^"]*\)"/"German_Middle_High"\1"\2\3\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([cOoÖoUuÜü]\)hl\([^"]*\)"/"German_Middle_High"\1"\2\3hel\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Cc]\)her\([^"]*\)"/"German_Middle_High"\1"\2\3hære\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)hæree\([^"]*\)"/"German_Middle_High"\1"\2hære\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ww]\)eig\([^"]*\)"/"German_Middle_High"\1"\2\3ích\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Hh]\)aus\([^"]*\)"/"German_Middle_High"\1"\2\3ous\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)[uü]rn\([^"]*\)"/"German_Middle_High"\1"\2oren\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)onn\([^"]*\)"/"German_Middle_High"\1"\2unn\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ww]ei\)\(ss\|ß\)\([^"]*\)"/"German_Middle_High"\1"\2\3íz\5"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ll]\)and\([^"]*\)"/"German_Middle_High"\1"\2\3ant\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([lnr]\)s\(b[eëou]r[cg]\|br[uü]ck[e]*\|h[ao]us\)\([^"]*\)"/"German_Middle_High"\1"\2\3es\4\5"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ee]\)n\(b[eëou]r[cg]\|h[ao]us\)\([^"]*\)"/"German_Middle_High"\1"\2\3rn\4\5"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)d\(b[eëou]r[cg]\|h[ao]us\)\([^"]*\)"/"German_Middle_High"\1"\2t\3\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([UuÜü]\)ss\([^"]*\)"/"German_Middle_High"\1"\2\3z\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Nn]\)ord\([^"]*\)"/"German_Middle_High"\1"\2\3ort\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)frau\([^"]*\)"/"German_Middle_High"\1"\2vrouw\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)Frau\([^"]*\)"/"German_Middle_High"\1"\2Vrouw\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ll]\)eu\([^"]*\)"/"German_Middle_High"\1"\2\3iu\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Ff]\)fen\([^"]*\)"/"German_Middle_High"\1"\2\3en\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)G\([^"]*\)"/"German_Middle_High"\1"\2Ch\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)Is\([^"]*\)"/"German_Middle_High"\1"\2Ís\3"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Bb]\)[eo]r[cg]\([^"]*\)"/"German_Middle_High"\1"\2\3ërc\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)\([Bb]\)rück[e]*\([^"]*\)"/"German_Middle_High"\1"\2\3rucke\4"/g' "${LOCATIONS_FILE}"
sed -i 's/"German_Middle_High"\(.*\)"\([^"]*\)au\(is\)*"/"German_Middle_High"\1"\2öu\3"/g' "${LOCATIONS_FILE}"
