name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (${{matrix.config.mod_game_id}})
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        config:
          - { mod_game_id: 'CK3',     steam_app_id: '1158310',  steam_item_id: '2217534250', mod_dir_name: 'more-cultural-names'      }
          - { mod_game_id: 'CK3AEP',  steam_app_id: '1158310',  steam_item_id: '2830250537', mod_dir_name: 'aep-more-cultural-names'  }
          - { mod_game_id: 'CK3ATHA', steam_app_id: '1158310',  steam_item_id: '3097513782', mod_dir_name: 'atha-more-cultural-names' }
          - { mod_game_id: 'CK3CE',   steam_app_id: '1158310',  steam_item_id: '2834102740', mod_dir_name: 'ce-more-cultural-names'   }
          - { mod_game_id: 'CK3CMH',  steam_app_id: '1158310',  steam_item_id: '2813306520', mod_dir_name: 'cmh-more-cultural-names'  }
          - { mod_game_id: 'CK3IBL',  steam_app_id: '1158310',  steam_item_id: '2490281800', mod_dir_name: 'ibl-more-cultural-names'  }
          - { mod_game_id: 'CK3MBP',  steam_app_id: '1158310',  steam_item_id: '2630872947', mod_dir_name: 'mbp-more-cultural-names'  }
          - { mod_game_id: 'CK3SoW',  steam_app_id: '1158310',  steam_item_id: '2724606810', mod_dir_name: 'sow-more-cultural-names'  }
          - { mod_game_id: 'CK3TBA',  steam_app_id: '1158310',  steam_item_id: '2821052607', mod_dir_name: 'tba-more-cultural-names'  }
          - { mod_game_id: 'CK3TFE',  steam_app_id: '1158310',  steam_item_id: '2690444295', mod_dir_name: 'tfe-more-cultural-names'  }
          - { mod_game_id: 'HOI4',    steam_app_id: '394360',   steam_item_id: '2459257386', mod_dir_name: 'more-cultural-names'      }
          - { mod_game_id: 'HOI4MDM', steam_app_id: '394360',   steam_item_id: '2826972160', mod_dir_name: 'mdm-more-cultural-names'  }
          - { mod_game_id: 'HOI4TGW', steam_app_id: '394360',   steam_item_id: '2725885905', mod_dir_name: 'tgw-more-cultural-names'  }
          - { mod_game_id: 'IR',      steam_app_id: '859580',   steam_item_id: '2219177532', mod_dir_name: 'more-cultural-names'      }
          - { mod_game_id: 'IR_ABW',  steam_app_id: '859580',   steam_item_id: '2829772740', mod_dir_name: 'abw-more-cultural-names'  }
          - { mod_game_id: 'IR_AoE',  steam_app_id: '859580',   steam_item_id: '2753371253', mod_dir_name: 'aoe-more-cultural-names'  }
          - { mod_game_id: 'IR_INV',  steam_app_id: '859580',   steam_item_id: '2827761791', mod_dir_name: 'inv-more-cultural-names'  }
          - { mod_game_id: 'IR_TBA',  steam_app_id: '859580',   steam_item_id: '2827468261', mod_dir_name: 'tba-more-cultural-names'  }

    steps:
    - name: Prepare
      run: |
          mkdir "${{matrix.config.mod_game_id}}"
          wget "https://github.com/hmlendea/more-cultural-names/releases/download/${{github.ref_name}}/mcn_${{matrix.config.mod_game_id}}_${GITHUB_REF:11}.zip" -O "${{matrix.config.mod_game_id}}.zip"
          unzip "${{matrix.config.mod_game_id}}.zip" -d "${{matrix.config.mod_game_id}}/"

    - name: Upload
      uses: hmlendea/steam-workshop-update@latest
      with:
        appid: ${{matrix.config.steam_app_id}}
        itemid: ${{matrix.config.steam_item_id}}
        path: "${{matrix.config.mod_game_id}}/${{matrix.config.mod_dir_name}}/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_2FASEED: ${{secrets.STEAM_2FASEED}}

    - name: Cooldown
      run: |
          COOLDOWN_LENGTH_SEC=30
          echo "Sleeping for ${COOLDOWN_LENGTH_SEC} to avoid Steam authentication rate-limiting..."
          sleep ${COOLDOWN_LENGTH_SEC}
